/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'matth' at '03/05/17 15:06' with Gradle 2.14
 *
 * @author matth, @date 03/05/17 15:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
