import nc.hightest.sandbox.Library;
import nc.hightest.sandbox.Main;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'matth' at '03/05/17 15:06' with Gradle 2.14
 *
 * @author matth, @date 03/05/17 15:06
 */
public class LibraryTest {
    @Test public void testMainMethod() {
        Main classUnderTest = new Main();
        assertTrue("Methode main should return 'true'", classUnderTest.main(""));
    }
}
